(() => {
  'use strict';
  const SB=window.StockBattle; let chart;
  const num=v=>Number(v||0), shares=p=>num(p.shares_owned||1);
  const initialStockAsset=p=>num(p.purchase_price)*shares(p);
  const currentStockAsset=(p,close)=>num(close)*shares(p);
  function completeDates(b){const dates=[...new Set(b.prices.map(p=>p.trade_date))].sort();return dates.filter(d=>b.players.every(pl=>b.prices.some(p=>p.player_id===pl.id&&p.trade_date===d)));}
  function rows(b,date){return b.players.map(player=>{const price=date?b.prices.find(p=>p.player_id===player.id&&p.trade_date===date):null;const initial=initialStockAsset(player);const asset=price?currentStockAsset(player,price.close_price):null;const profit=asset===null?null:asset-initial;const growth=price&&num(player.purchase_price)>0?(num(price.close_price)-num(player.purchase_price))/num(player.purchase_price)*100:null;return{player,price,initial,asset,profit,growth};}).sort((a,b)=>(b.growth??-Infinity)-(a.growth??-Infinity));}
  function renderRanking(b,latest){const data=rows(b,latest);document.getElementById('ranking-cards').innerHTML=data.map((r,i)=>`<article class="compact-rank-row" style="--player-color:${SB.escapeHtml(r.player.color)}"><div class="member-cell"><span class="compact-rank-number">${r.growth===null?'—':i+1}</span><div><strong>${SB.escapeHtml(r.player.nickname)}</strong><small>${SB.escapeHtml(r.player.security_name)} / ${SB.escapeHtml(r.player.security_code)}</small></div></div><div data-label="取得単価"><strong>${SB.yen(r.player.purchase_price)}</strong><small>${SB.number(shares(r.player))}株</small></div><div data-label="現在値"><strong>${r.price?SB.yen(r.price.close_price):'—'}</strong><small>${SB.number(shares(r.player))}株</small></div><div data-label="成長率"><strong class="${r.growth===null?'':r.growth>=0?'positive':'negative'}">${r.growth===null?'未登録':SB.pct(r.growth)}</strong><small>${r.profit===null?'損益 —':SB.signedYen(r.profit)}</small></div><div data-label="現在資産"><strong>${r.asset===null?'—':SB.yen(r.asset)}</strong></div></article>`).join('');
    const sharedCash=num(b.carryover_cash||0); const initialTotal=data.reduce((s,r)=>s+r.initial,0)+sharedCash; if(!latest){['total-assets','total-profit','total-growth'].forEach(id=>document.getElementById(id).textContent='—');return;}
    const total=data.reduce((s,r)=>s+r.asset,0)+sharedCash, profit=total-initialTotal, growth=initialTotal?profit/initialTotal*100:0;
    document.getElementById('total-assets').textContent=SB.yen(total);const pe=document.getElementById('total-profit');pe.textContent=SB.signedYen(profit);pe.className=profit>=0?'positive':'negative';const ge=document.getElementById('total-growth');ge.textContent=SB.pct(growth);ge.className=growth>=0?'positive':'negative';
  }
  function renderChart(b){const labels=[...new Set(b.prices.map(p=>p.trade_date))].sort();const empty=!labels.length;document.getElementById('empty-chart').classList.toggle('hidden',!empty);document.querySelector('.chart-wrap').classList.toggle('hidden',empty);if(chart)chart.destroy();if(empty)return;
    chart=new Chart(document.getElementById('growth-chart'),{type:'line',data:{labels,datasets:b.players.map(player=>{const purchase=num(player.purchase_price);return{label:player.nickname,data:labels.map(date=>{const p=b.prices.find(x=>x.player_id===player.id&&x.trade_date===date);return !p||purchase<=0?null:(num(p.close_price)-purchase)/purchase*100;}),borderColor:player.color,backgroundColor:player.color,borderWidth:3,tension:.25,spanGaps:true,pointRadius:2.5,pointHoverRadius:6};})},options:{responsive:true,maintainAspectRatio:false,interaction:{mode:'index',intersect:false},plugins:{legend:{position:'bottom',labels:{usePointStyle:true,boxWidth:8,padding:10,font:{size:11}}},tooltip:{callbacks:{label:ctx=>`${ctx.dataset.label}: ${SB.pct(ctx.parsed.y)}`}}},scales:{y:{title:{display:true,text:'成長率（%）'},grid:{color:ctx=>ctx.tick.value===0?'#667085':'#e6ebf0'}},x:{title:{display:true,text:'日付'},grid:{display:false},ticks:{maxTicksLimit:7}}}}});
  }
  async function init(){SB.bindNav();if(!SB.configured||!SB.token){document.getElementById('missing-battle').classList.remove('hidden');return;}try{const b=await SB.loadBattle();document.getElementById('dashboard').classList.remove('hidden');document.getElementById('battle-title').textContent=b.name;document.getElementById('battle-period').textContent=`${SB.dateText(b.start_date)} 〜 ${b.end_date?SB.dateText(b.end_date):'終了日未設定'}`;const dates=completeDates(b),latest=dates.at(-1)||null;document.getElementById('latest-date').textContent=latest?SB.dateText(latest):'未登録';document.getElementById('price-days').textContent=`${dates.length}日`;renderRanking(b,latest);renderChart(b);document.getElementById('copy-link').onclick=async()=>{await navigator.clipboard.writeText(location.href);SB.showMessage('共有URLをコピーしました。');};}catch(e){document.getElementById('missing-battle').classList.remove('hidden');SB.showMessage(e.message||'読み込めませんでした。','error');}}
  init();
})();
